# Generated by Django 4.2.3 on 2023-07-27 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garhdony_app.LARPStrings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garhdony_app', '0040_auto_20170517_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='title_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_of', to='garhdony_app.genderizedkeyword', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='characterstat',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Game Complete'),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='usernamesuffix',
            field=models.CharField(max_length=50, verbose_name='Username Suffix'),
        ),
        migrations.AlterField(
            model_name='gametemplate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='genderizedkeyword',
            name='category',
            field=models.CharField(blank=True, choices=[('title', 'title'), ('name', 'name'), ('pronoun', 'pronoun')], max_length=10),
        ),
        migrations.AlterField(
            model_name='logisticaltask',
            name='form_type',
            field=models.CharField(blank=True, choices=[('confirmation', 'confirmation'), ('photo', 'photo'), ('pregame_party', 'pregame_party'), ('travel_survey', 'travel_survey'), ('housing_survey', 'housing_survey')], max_length=30),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='gender_field',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OP', 'Opposite of'), ('EQ', 'Same as')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='nonplayercharacter',
            name='notes',
            field=garhdony_app.LARPStrings.LARPTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='costuming_hint',
            field=garhdony_app.LARPStrings.LARPTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playercharacter',
            name='default_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='pregame_party_rsvp',
            field=models.BooleanField(null=True, verbose_name=b'Will you be attending?'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='content_type',
            field=models.CharField(choices=[('html', 'html'), ('application/pdf', 'pdf'), ('image/png', 'png')], default='html', max_length=50),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='filename',
            field=models.CharField(max_length=300, verbose_name='Internal Name (unique)'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='name',
            field=garhdony_app.LARPStrings.LARPTextField(verbose_name='Printed Name'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='preview_description',
            field=garhdony_app.LARPStrings.LARPTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sheetrevision',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='car_status',
            field=models.CharField(choices=[('has car', "I own a car and can help drive others up (we'll reimburse expenses + some wear and tear)"), ('personal car', 'I own a car but will only drive myself'), ('can rent', "I don't own a car, but I am at least 25 and willing to rent a car (we will pay, of course)"), ('can rent under 25', "I don't own a car, but I am under 25 and willing to drive someone else's car"), ("can't drive", 'I cannot or do not want to drive')], max_length=200, verbose_name=b'What is your car status?'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='departure_location',
            field=models.TextField(verbose_name='Where will you be leaving from?'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='departure_time',
            field=models.TextField(verbose_name='What time will you be ready to leave?'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='dinner_status',
            field=models.CharField(choices=[('going', "I'll come to dinner to share stories!"), ("can't", 'I need to be back early.')], max_length=200, verbose_name=b"Do you think you'll come to the wrap-up dinner on Sunday, or go straight home?"),
        ),
    ]
