# Generated by Django 4.2.3 on 2023-08-06 19:35

from django.db import migrations, models
import django.db.models.deletion
import garhdony_app.LARPStrings

# create new timeline for each game.
def create_timelines(apps, schema_editor):
    GameInstance = apps.get_model("garhdony_app", "GameInstance")
    Timeline = apps.get_model("garhdony_app", "Timeline")
    for game in GameInstance.objects.all():
        timeline = Timeline(name=game.name)
        timeline.save()
        game.timeline = timeline
        game.save()

class Migration(migrations.Migration):

    dependencies = [
        ('garhdony_app', '0041_alter_character_last_name_alter_character_title_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order_number']},
        ),
        migrations.AlterModelOptions(
            name='sheetcolor',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='sheetstatus',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='sheettype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['timeline', 'year', 'month', 'day']},
        ),
        migrations.RenameField(
            model_name='timelineevent',
            old_name='default_description',
            new_name='internal_name',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characterstat',
            name='stat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garhdony_app.characterstattype'),
        ),
        migrations.CreateModel(
            name='TimelineViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='garhdony_app.timeline')),
            ],
            options={
                'ordering': ['timeline', 'name'],
            },
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='timeline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='game', to='garhdony_app.timeline'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='timeline',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet', to='garhdony_app.timelineviewer'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='timeline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garhdony_app.timeline'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timelineevent',
            unique_together={('timeline', 'internal_name')},
        ),
        migrations.CreateModel(
            name='TimelineEventDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', garhdony_app.LARPStrings.LARPTextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='garhdony_app.timelineevent')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='garhdony_app.timelineviewer')),
            ],
            options={
                'ordering': ['event__timeline', 'event__year', 'event__month', 'event__day', 'viewer__name'],
                'unique_together': {('event', 'viewer')},
            },
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='game',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='name',
        ),
        migrations.DeleteModel(
            name='TimelineEventCharacterDescription',
        ),
        migrations.RunPython(create_timelines),
    ]
