# Generated by Django 4.2.3 on 2023-08-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garhdony_app', '0042_timeline_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['game', '-char_type', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='characterstattype',
            options={'ordering': ['game', 'name']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['owner', 'order_number']},
        ),
        migrations.AlterModelOptions(
            name='genderizedkeyword',
            options={'ordering': ['category', 'male']},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['game', 'name']},
        ),
        migrations.AlterModelOptions(
            name='sheetstatus',
            options={'ordering': ['game', 'sort_order']},
        ),
        migrations.AlterField(
            model_name='embeddedimage',
            name='filename',
            field=models.CharField(max_length=210),
        ),
        migrations.AlterUniqueTogether(
            name='embeddedimage',
            unique_together={('filename', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='sheet',
            unique_together={('game', 'filename')},
        ),
    ]
