# Generated by Django 4.2.3 on 2023-08-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garhdony_app', '0045_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['timeline', 'year', 'month', 'day']},
        ),
        migrations.RenameField(
            model_name='timelineeventdescription',
            old_name='unique_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='default_description',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='viewers',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='internal_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineviewer',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
