# Generated by Django 4.2.3 on 2023-08-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garhdony_app', '0046_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineeventdescription',
            options={'ordering': ['event__timeline', 'event__year', 'event__month', 'event__day']},
        ),
        migrations.RenameField(
            model_name='timelineevent',
            old_name='internal_description',
            new_name='internal_name',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='timeline',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='game', to='garhdony_app.timeline'),
        ),
    ]
